### ISSUE TITLE
[REQ] fix license on GH

### ISSUE THREAD

**Issue by forart** [daveschere/ffmpeg-guitar-scripts#1]
Hi there, 1st of all thanks for your awesome (voluntary) work !

Since we've doxed this git in our [HyMPS project](https://github.com/forart/HyMPS) (under [Effects](https://github.com/forart/HyMPS/blob/main/AudioFXs.md#audio---effects-) - [Guitar](https://github.com/forart/HyMPS/blob/main/Guitar.md#audio---effects---guitar-) - [DSPs](https://github.com/forart/HyMPS/blob/main/Guitar.md#dsps-) section), can you please fix licensing terms for it ?

Our "problem" is that the relative license badge isn't generated correctly:

![](https://flat.badgen.net/github/license/daveschere/ffmpeg-guitar-scripts)
(generator URL: https://flat.badgen.net/github/license/daveschere/ffmpeg-guitar-scripts)

This could be easily fixed by choosing a "correct" license file through the GH's wizard.

Although it may sounds like a minor aspect, this may help other devs to understand how reuse your code in other open projects and vice-versa that's a determining factor for the success and longevity of your project.

Last but not least, let us know how - in your opinion - we could improve our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Thanks in advance.

**Comment by daveschere** [comment]
https://github.com/daveschere/ffmpeg-guitar-scripts/blob/main/LICENSE

MIT license.

Glad it was of some use to you.

**Comment by forart** [comment]
WOW, thanks for the quick "fix" !

As you can see (above too) the badge is now generated correctly.

We've recently introduced a "dev-oriented" grouping+sorting, so projects are now listed by the following sorting chain:

Section > Subsection > Language > License > Alphabetical

Let us know if your git is rightly placed or you need a different one.

Do you think this new approach could foster collaboration between projects better? Any observation/suggestions?

Thanks again and, if you like/need, let us know (by participating in [our discussions](https://github.com/forart/HyMPS/discussions) too) how can we better support listed projects.

Last but not least, Happy New Year !
